name: SFTP Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# thank you, wlixcc. <3

jobs:
  deploy_job:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'zkldi'
          server: '157.245.40.246'
          private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './static/*'
          remote_path: '/home/zkldi/ktchi-api' #make sure dir exist
          args: '-o ConnectTimeout=5'
